#!/bin/bash


# COPYQ
copyq --start-server


# XDG-PORTAL-HYPRLAND LAUNCHSCRIPT
sleep 1
killall -e xdg-desktop-portal-hyprland
#killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
#/usr/libexec/xdg-desktop-portal-hyprland &
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &


# POLKIT-KDE-AUTHENTICATION-AGENT-1
/usr/lib/polkit-kde-authentication-agent-1


# DBUS-UPDATE-ACTIVATION-ENVIRONMENT
dbus-update-activation-environment --systemd --all
