#!/bin/bash

backup=$HOME/dotfiles/backup.latest/
rm -rf $backup


dotfiles=$(cat ~/.config/dotfiles/repositoryLocalPath.cache)




####################################################################################
####################################################################################
####################################################################################



update_config() {

	config_dir="$dotfiles/dotfiles/.config/"

	echo -e "now copying all folders from '$config_dir' to '~/.config'\n"

	for dir in $(ls -A "$config_dir"); do
		echo "CHECKING $dir:"
		if [[ -d "$config_dir/$dir" ]]; then
			echo -e "'$dir' is a diretory. copying to home-directory.\n"
			cp -r "$HOME/.config/$dir" "$backup/"
			rm -rf "$HOME/.config/$dir"
			cp -r "$config_dir/$dir" "$HOME/.config/"
		else
			echo -e "skipping: '$dir' is a file.\n"
		fi
	done
}

copy_wallpaper_folder() {

	source="$dotfiles/dotfiles/wallpaper"
	target="$HOME/.wallpaper"

	mkdir -p "$target"
	echo -e "now copying folder as a whole from '$source' to '$target'\n"
	cp -r "$source"/* "$target/"
	echo -e "finished copying folder from '$source' to '$target'\n"
}

copy_files_to_home() {

	source="$dotfiles/dotfiles/"
	target="$HOME"

	for file in $(ls -A "$source"); do
		echo "CHECKING $file:"
		if [[ -f "$source/$file" ]]; then
			echo -e "'$file' is a file. copying to home-directory.\n"
			cp -r "$HOME/$file" "$backup/"
			rm -rf "$HOME/$file"
			cp -r "$source/$file" "$target/"
		else
			echo -e "skipping: '$file' is a directory.\n"
		fi
	done
}

update_config
copy_wallpaper_folder
copy_files_to_home

echo "Installation complete."