#!/bin/bash

# ===================================================== #
#                                                       #
# This script is deprecated! 							#
# It used to fulfill the following function: 			#
# 														#
# I wanted to be able to have all of my config-files 	#
# in one folder (my dotfiles git repository).			#
# 														#
# This way I am able to keep the git repository up to 	#
# date at all times, as well as making it easier to 	#
# edit my configuration files in an IDE.				#
# 														#
# This script "synced" the local copy of my repository	#
# to all the corresponding folders (by copying the 		#
# files to the correct paths in my system).				#
# 														#
# By binding the script to a keyboard shortcut, I can 	#
# quickly check the effects of my changes. 				#
# Particularly useful when ricing.						#
# 														#
# Deprecated because:									#
# Setup changed too much. Needs to be updated.			#
# Could (and should) be done better as a whole.			#
#                                                       #
# ===================================================== #

# ===================================================== #

backup=$HOME/dotfiles/backup.latest/
rm -rf $backup

dotfiles=$(cat ~/.config/dotfiles/repositoryLocalPath.cache)

# ===================================================== #

update_config() {

	config_dir="$dotfiles/dotfiles/.config/"

	echo -e "now copying all folders from '$config_dir' to '~/.config'\n"

	for dir in $(ls -A "$config_dir"); do
		echo "CHECKING $dir:"
		if [[ -d "$config_dir/$dir" ]]; then
			echo -e "'$dir' is a diretory. copying to home-directory.\n"
			cp -r "$HOME/.config/$dir" "$backup/"
			rm -rf "$HOME/.config/$dir"
			cp -r "$config_dir/$dir" "$HOME/.config/"
		else
			echo -e "skipping: '$dir' is a file.\n"
		fi
	done
}

copy_wallpaper_folder() {

	source="$dotfiles/dotfiles/wallpaper"
	target="$HOME/.wallpaper"

	mkdir -p "$target"
	echo -e "now copying folder as a whole from '$source' to '$target'\n"
	cp -r "$source"/* "$target/"
	echo -e "finished copying folder from '$source' to '$target'\n"
}

copy_files_to_home() {

	source="$dotfiles/dotfiles/"
	target="$HOME"

	for file in $(ls -A "$source"); do
		echo "CHECKING $file:"
		if [[ -f "$source/$file" ]]; then
			echo -e "'$file' is a file. copying to home-directory.\n"
			cp -r "$HOME/$file" "$backup/"
			rm -rf "$HOME/$file"
			cp -r "$source/$file" "$target/"
		else
			echo -e "skipping: '$file' is a directory.\n"
		fi
	done
}

# ===================================================== #

update_config
copy_wallpaper_folder
copy_files_to_home

echo "Installation complete."